# Generated by Django 5.0.1 on 2024-03-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
