# Generated by Django 5.0.1 on 2024-03-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0011_addons_remove_customer_address_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addons',
        ),
    ]
